/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thread.sample;

public class App {

    public static void main(String[] args) {
        Thread thread1 = new SubThread();
        thread1.start();
    }
}
